### ISSUE TITLE
ID for xxx is already registered?!

### ISSUE THREAD

**Issue by ghost** [eamodio/vscode-gitlens#606]
- GitLens Version: 9.3.0
- VSCode Version: 1.30.1 (User setup)
- OS Version: Windows 10 (Professional, x86)

Steps to Reproduce:

1. Open a repository based on your local PC, then use the command below to sync with your remote one:

**git pull --rebase [your remote rep name] [your remote branch name]:[your local branch name]**

![errorinterface](https://user-images.githubusercontent.com/40081831/50665975-b7fd3000-0fed-11e9-8e9a-7c831904995c.PNG)

2. There'll be an error thrown out (plz see the image below, on the right bottom corner).

3. Then the Git tree cannot be expand until I click "refresh" button:
![err2](https://user-images.githubusercontent.com/40081831/50666087-24782f00-0fee-11e9-83ab-d5e9d0396596.PNG)

4. Here're some logs:
[Log_ForGit.txt](https://github.com/eamodio/vscode-gitlens/files/2725551/Log_ForGit.txt)
[Log_forGitLen.txt](https://github.com/eamodio/vscode-gitlens/files/2725552/Log_forGitLen.txt)

**Comment by Maledong** [comment]
@eamodio：OK, it seems fixed. MANY THANKS FOR YOUR QUICK REPLY!!!!

**Comment by Maledong** [comment]
@eamodio：Just for a confirmation……This bug is still open?

**Comment by Maledong** [comment]
This bug is still open, and this problem still occurs……So isn't this fixed (Just for a confirm)...

**Comment by eamodio** [comment]
Yeah, I had to roll back the first "fix", and I'm quite convinced there is a vscode bug here -- but I've had a hard time pinning it down. I am also hoping once vscode finishes moving extensions over to their new tree implementation that the issue will just go away 😄 

But its terribly annoying -- I just don't have an idea how to fix it at this point :(

**Comment by Maledong** [comment]
OK no problem, just for a confirm and don't worry, frankly speaking, I can continue using that :)

**Comment by eamodio** [comment]
👍 Also at least now the refresh button on the view will fix everything too.

**Comment by Maledong** [comment]
@eamodio：No problem, I'll try to make a report to Microsoft (VSCode)

**Comment by erfurtjohn** [comment]
I also ran into this issue, thanks for the information in this topic.

**Comment by mydmdm** [comment]
still got the same issue  (vscode 1.37.1, gitlen 9.9.3)
 
> Element with id gitlens:repository(...) is already registered

**Comment by shanmugharajk** [comment]
I am also getting the same issue (vscode 1.37.1, gitlen 9.9.3)

**Comment by alexleduc76** [comment]
I have it too. (vscode 1.39.0, gitlen 10.1.1)

**Comment by jg572h** [comment]
Wondering if there has been any movement on this issue?  I get this message every day.  (VSCode 1.48.0, GitLens v10.2.2).  Thanks.

**Comment by eamodio** [comment]
For those running into this issue, do you have any reproducible cases? I have seen it every now and again, but nothing that I can trap and debug.

**Comment by jg572h** [comment]
For me it happens right after I open my project (an Angular project).  All I have to do is click on the GitLens icon in the sidebar, and the message comes up.
![image](https://user-images.githubusercontent.com/46976568/90429913-8aff7300-e094-11ea-9961-46cadc004bf5.png)

This particular project has a lot of branches, in case that is helpful.
Another thing is that the project is part of a larger project, and both this project and the larger project have VS Code workspaces.

Is there a cache somewhere that I could try to clear?

**Comment by eamodio** [comment]
@jg572h are these repos open source?

**Comment by jg572h** [comment]
Sorry, they're not.

**Comment by eamodio** [comment]
I fixed this issue in VS Code -- so this should no longer happen.

**Comment by skelesp** [comment]
@eamodio : In which version of vs code is this fixed?

**Comment by eamodio** [comment]
@skelesp I think it was in 1.50. Are you still seeing this? I've seen a report recently (and have seen other related behavior) that makes me think it was re-broken in VS Code recently (1.52)

**Comment by skelesp** [comment]
@eamodio : working on 1.52.1 and I'm still seeing the "element with id..." message. So it must be rebroken again.

**Comment by eamodio** [comment]
Can you provide details on when/how you are experiencing it? And also the exact error message?

**Comment by njbbaer** [comment]
I am also getting this error with v1.53.2 of VSCode and v11.2.1 of GitLens
<img width="462" alt="Screen Shot 2021-02-23 at 11 44 55 PM" src="https://user-images.githubusercontent.com/5005914/108965038-27509680-7631-11eb-9251-b5b681486955.png">

**Comment by eamodio** [comment]
@njbbaer Can you provide details on when/how you are experiencing it? And is it always with tags?

**Comment by eamodio** [comment]
I'm locking this issue, as the original case was resolved. Please open new issues for any new cases. Or add to #1405.
